### ISSUE TITLE
websocket cluster

### ISSUE THREAD

**Issue by phra** [kamilmysliwiec/nest#1]
hi,

i see that you have included by default socket.io.. i'm thinking about a cluster scenario where i have a load balancer that is splitting load between nodes in a round-robin fashion. in that case the HTTP fallback of socket.io it will fail because requests will hit everytime different nodes, that will require to restablish the connection + re-auth. (basically they will become useless).
in the past i resolved this issue keeping different servers for APIs calls and WS interactions in order to put a round robin LB on the APIs and a IP hash LB for WS.

do you have thinked about this issue? if the connection is a real WS one (and not the HTTP fallback) it will persist also through a round robin LB?

thanks.

**Comment by kamilmysliwiec** [comment]
Hi @phra,

I'm sorry that you had to wait so much time for the answer :( I didn't think about this scenario yet. Nest use plain socket.io by default without any additional plugins. It means that each common behaviour of this library will works equivalently in Nest.

**Comment by phra** [comment]
@kamilmysliwiec if you are using the default settings they will include the http fallback that i you have to disable to work correctly with clusters.
you can see [this issue](https://github.com/mean-expert-official/loopback-sdk-builder/issues/368) for more infos.

**Comment by MickL** [comment]
If you cluster between different servers your load balancer has to support sticky sessions for http and websockets. I would not recommend to disable http unless you support only modern browsers. Socket.io for example always starts with an http connection and upgrades to better connections(Websockets) if supported.
