### ISSUE TITLE
Nest Middleware doesn't properly throws HttpException on the backend

### ISSUE THREAD

**Issue by kevde** [kamilmysliwiec/nest#106]
I have a code of a custom NestMiddleware and I was trying to throw an exception:

```
@Middleware()
export class MultipartMiddleware implements NestMiddleware {
  constructor(private multipartReader: MultipartReader) {}

  resolve(): (req, res, next) => void {
    return async(req, res, next) => {
      this.multipartReader.parseRequest(req).then((formData:any) => {
        req.body = _.merge(formData.fields, formData.files);
        next();
      }).catch((error) => {
        throw new HttpException(error, 500);
      })
    }
  }
}
```

I was expecting for the route to send a error 500 but this error was displayed:

`(node:5272) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): [object Object]
`

**Comment by cojack** [comment]
@kevde try:

```typescript
      }).catch((error) => {
        const err = new HttpException(error, 500);
        next(err);
      })
```

**Comment by kamilmysliwiec** [comment]
Hey @kevde,
It's not a Nest issue. You only have to replace `then` with async/await. In your example, you're trying to throw exception within `catch` operator. It returns another `Promise` with exception, which in fact - is unhandled.
