### ISSUE TITLE
Create Module for CLI Usage

### ISSUE THREAD

**Issue by chrissm79** [kamilmysliwiec/nest#107]
Is there a way to create a module for use in a cli script? Just doing a bit of digging around and it seems that the only way to create a Nest app is w/ Express. I'm looking for something like the `createTestingModule` where I can pass it a module and it handles all the dependencies w/out firing up a server.

This framework is 💯 btw, thanks!

**Comment by cojack** [comment]
@chrissm79 not necessary at all to use it as express app, try to call `app.init()` instead of `app.listen()`

**Comment by chrissm79** [comment]
@cojack Thanks, that worked!
