### ISSUE TITLE
[Documentation] ID issue

### ISSUE THREAD

**Issue by alexcorvi** [kamilmysliwiec/nest#11]
On [this page](https://kamilmysliwiec.gitbooks.io/nest/content/quick-start/components.html) You're looking for users using the `find` method, but the IDs are stored in the service as numbers and the received param will be a string. So here's a quick fix:

This:

```typescript
    @RequestMapping({ path: '/:id' })
    getUser(req, res) {
        this.usersService.getUser(req.params.id)
            .then((user) => res.status(200).json(user));
    }
```

Needs to change to this:
```typescript
    @RequestMapping({ path: '/:id' })
    getUser(req, res) {
        this.usersService.getUser(Number(req.params.id)) // simply casted to number
            .then((user) => res.status(200).json(user));
    }
```

I know it's just an example for demonstration purposes, but it should work nonetheless.

**Comment by juandav** [comment]
use @Get() or @Get('/:id')

**Comment by kamilmysliwiec** [comment]
Hi @alexcorvi,
You're right, thanks!
I changed:

```
const user = await this.usersService.getUser(req.params.id);
```
to:
```
const user = await this.usersService.getUser(+req.params.id);
```
Now, it should works fine.
