### ISSUE TITLE
Access express from ApplicationModule or inject own service into ApplicationModule

### ISSUE THREAD

**Issue by makislav** [kamilmysliwiec/nest#110]
Hello everyone,

I am new to this Framework and got the following problem: 

I am using TypeORM to connect to the database which is running as a service and gets injected into all components/controllers where it is needed - everything is running fine.

Now I tried to implement passport with a local strategy: I want to check the userdetails from my database using the TypeORM service I've already created - and that's where my problem starts: I want to use **one** database connection in the whole application, as I can't instantiate the TypeORM connection pool more than once (https://github.com/typeorm/typeorm/issues/592).

Is there a best practice for those kind of case? Can I instantiate my TypeORM Service outside the main ApplicationModule and then inject it into it in order to use it in both, passport and the app itself?

Or is it possible to access the express instance from within the ApplicationModule in order to make passport use the TypeORM service instantiated by nestjs?

Any help would be very appreciated.

**Comment by cojack** [comment]
@makislav your problem will be solved if @kamilmysliwiec will accept my PR #100 , then you will be able to do what you want.

**Comment by makislav** [comment]
Hey @cojack, I've already taken a look at it, there's still the question how I can combine the created TypeORM service with passport / the instance of express.

**Example**
```ts
import "reflect-metadata";

import * as express from 'express';
import * as compression from 'compression';
import * as bodyParser from 'body-parser';
import * as cookieParser from 'cookie-parser';
import * as expressSession from 'express-session';
import * as passport from "passport";
import * as connectMongo from "connect-mongo";

import {NestFactory} from '@nestjs/core';
import {ApplicationModule} from './app/app.module';
import {Environment} from "./app/shared/config/config";
import {PassportService} from "./app/shared/services/passport/passport.service";

//
new PassportService(passport);

// Middleware
const instance = express();
instance.use(compression());
instance.use(bodyParser.json());
instance.use(cookieParser());
instance.use(expressSession({
    secret: Environment.session.secret,
    resave: false,
    saveUninitialized: false
}));
instance.use(passport.initialize());
instance.use(passport.session());

const app = NestFactory.create(ApplicationModule, instance);
app.listen(3000, () => console.log('Application is listening on port 3000.'));
```
This is my current  initialization file. I am using PassportService (similar to the example in the docs) to tell passport what it has to do (i.e. query the database). So even if your PR makes it possible to wait for a successful initialization of services etc **inside** the app, there's still the question how I can tell my PassportService (which is outside of the app) how to use the TypeORM Connection **inside** the app.

(Or how to tell passport/express what to do from **inside** of the ApplicationModule)

**Comment by cojack** [comment]
@makislav Im sorry but I was wrong about your situation. This I guess should be modified to be used inside of nest. I did not implement passport yet but it looks like it might work when you will pass the PassportService to your AppModule and try to initialize it in constructor or something like this.

**Comment by kamilmysliwiec** [comment]
Hey @makislav, 
You only have to move your passport strategy class inside Nest, something like this:

```typescript
@Component()
export class JwtStrategy extends Strategy {
   constructor(
        @Inject(JWTConfigToken) config: JWTConfig,
        private readonly authService: AuthService) {

        super({
            jwtFromRequest: ExtractJwt.fromAuthHeader(),
            passReqToCallback: true,
            secretOrKey: config.secretOrKey,
        }, async (req, payload, next) => await this.verify(req, payload, next));

        passport.use(this);
    }
    /*....*/
}
```

**Comment by juan-manuel-alberro** [comment]
@kamilmysliwiec I've the same issue and that worked, thanks! 
For `express-session` we need to do something special in Nest? Because the login is successful but `req.isAuthenticated()` is always `false`.

**Comment by a-pavlov-parc** [comment]
Hey guys. Is there anywhere a full example of how to implement password jwt authorisation? I'd appreciate to have this

**Comment by adrien2p** [comment]
Hey ! You can see my repo you will find what you search

**Comment by a-pavlov-parc** [comment]
@adrien2p I see that. Good example. Thank you!

**Comment by adrien2p** [comment]
@a-pvlov-parc my pleasure
