### ISSUE TITLE
Typo in the docs

### ISSUE THREAD

**Issue by bradleyayers** [kamilmysliwiec/nest#114]
https://docs.nestjs.com/quick-start/first-controller.html

> In previuos section we set up

It should read:

> In the previous section we set up

I looked around for somewhere to open a PR, but couldn't find it here nor on gitbook.com

**Comment by LoicPoullain** [comment]
Also a typo at [https://docs.nestjs.com/quick-start/setup-application.html](https://docs.nestjs.com/quick-start/setup-application.html)

>  (we don't have any controlles or components right now)

instead of:

>  (we don't have any controllers or components right now)

**Comment by matthewharwood** [comment]
Also  Typo in the docs code: 

https://docs.nestjs.com/quick-start/setup-application.html
```
import { NestFactory } from '@nestjs/core';
import { ApplicationModule } from './app.module';

const app = NestFactory.create(ApplicationModule);
app.listen(3000, () => console.log('Application is listening on port 3000'))
```
`NestFactory.create(ApplicationModule);` returns a promise and therefore should be async/await or use with then.

**Comment by kamilmysliwiec** [comment]
Hello everyone,
Thanks! We have new docs now http://www.docs.nestjs.com. I suppose there's a lot of grammar issues, but I'm not so fluent, unfortunately :cry:.
