### ISSUE TITLE
Docs: links redirect to another domain

### ISSUE THREAD

**Issue by alexjoverm** [kamilmysliwiec/nest#117]
The following links redirect to kamilmysliwiec.gitbooks.io/* instead of docs.nestjs.com/*

![image](https://user-images.githubusercontent.com/5701162/28454931-4bffc126-6dfd-11e7-93ce-9cabb848e18b.png)

Additionally, where are the docs src to send PR?

**Comment by kamilmysliwiec** [comment]
Hi @alexjoverm,
Fixed! Thanks
