### ISSUE TITLE
[Documentation] Express Typing

### ISSUE THREAD

**Issue by alexcorvi** [kamilmysliwiec/nest#12]
It's really good to see a web framework that deals with TypeScript as a first class citizen! I'm really excited about this project because of this.

However, when turning the option: `noImplicitAny` in the `tsconfig.json` the compiler will produce warnings about a lot of the examples in the documentation.

I highly recommend adding Express TypeScript declarations to the examples like so:

```typescript

import {Request,Response,NextFunction} from "@types/express";


@Controller({})
export class UsersController {
	getAllUsers(req:Request, res:Response, next:NextFunction) {
		// will have auto completion, type safety ...etc
	}
}

```

**Comment by ThomRick** [comment]
To solve the problem:

```text
npm install --save-dev @types/express
```

I think we can close this issue.

**Comment by KerryRitter** [comment]
@ThomRick He's asking that the examples on https://kamilmysliwiec.gitbooks.io/nest/content/ add the Express types. Right now they just say:

```
@Get('/:id')
public async getUser(@Response() res, @Param('id') id) {
```

as opposed to

```
@Get('/:id')
public async getUser(@Response() res: Response, @Param('id') id) {
```

**Comment by jakub-gawlas** [comment]
unfortunately not possible to import `Request, Response` from `@types/express` and `nest.js` together, have to alias one of them
```js
import { Response, Request } from '@types/express';
import { 
  Response as Req, 
  Request as Res 
} from 'nest.js';
```

**Comment by ScottMGerstl** [comment]
When trying to do the above I get:

```
src/index.ts(1,8): error TS1192: Module '"C:/Development/me/nest-graph-api/node_modules/@types/express/index"' has no default export.
src/users/users.controller.ts(11,18): error TS4053: Return type of public method from exported class has or is using name 'Response' from external module "C:/Development/me/nest-graph-api/node_modules/@types/express-serve-static-core/index" but cannot be named.
src/users/users.controller.ts(17,18): error TS4053: Return type of public method from exported class has or is using name 'Response' from external module "C:/Development/me/nest-graph-api/node_modules/@types/express-serve-static-core/index" but cannot be named.
src/users/users.controller.ts(23,18): error TS4053: Return type of public method from exported class has or is using name 'Response' from external module "C:/Development/me/nest-graph-api/node_modules/@types/express-serve-static-core/index" but cannot be named.
```
Here is the code I'm trying to transpile

```
import { Response, Request } from '@types/express';
import { Controller, Get, Post, Request as Req, Response as Res, Param, Body, HttpStatus } from 'nest.js';
import { UsersService } from './users.service';

@Controller('users')
export class UsersController {

    constructor(private usersService: UsersService) {}

    @Get()
    public async getAllUsers(@Res() res: Response) {
        const users = await this.usersService.getAllUsers();
        return res.status(HttpStatus.OK).json(users);
    }

    @Get('/:id')
    public async getUser(@Res() res: Response, @Param('id') id) {
        const user = await this.usersService.getUser(id);
        return res.status(HttpStatus.OK).json(user);
    }

    @Post()
    public async addUser(@Res() res: Response, @Body('user') user) {
        const msg = await this.usersService.addUser(user);
        return res.status(HttpStatus.CREATED).json(msg);
    }
}

```

**Comment by kamilmysliwiec** [comment]
Since latest version `@Request()` and `@Response()` decorators have an aliases - `@Req()` and `@Res()` so there is no collision with express typings. About `@types/express`, I added short notice about it in the documentation.

**Comment by Mark-McCracken** [comment]
I found an issue with decorators being used on function parameters that might be related to this.

when using something like

```js
@Get('playlist')
  async getPlaylist(@Res() res) {
    res.send(playlist);
  }
```

This will only work so long as your typescript's tsconfig.json is targeting es2015 or higher, if targeting es5, this will throw an error like so:
```bash
[Nest] 17957   - 2017-8-2 22:14:37   [ExceptionsHandler] res.send is not a function
TypeError: res.send is not a function
    at PlaylistController.<anonymous> (/Users/mark.mccracken/Work/learning/angular/state-management/dist/server/playlist/playlist.controller.js:118:43)
    at step (/Users/mark.mccracken/Work/learning/angular/state-management/dist/server/playlist/playlist.controller.js:44:23)
    at Object.next (/Users/mark.mccracken/Work/learning/angular/state-management/dist/server/playlist/playlist.controller.js:25:53)
    at /Users/mark.mccracken/Work/learning/angular/state-management/dist/server/playlist/playlist.controller.js:19:71
    at Promise (<anonymous>)
    at __awaiter (/Users/mark.mccracken/Work/learning/angular/state-management/dist/server/playlist/playlist.controller.js:15:12)
    at PlaylistController.getPlaylist (/Users/mark.mccracken/Work/learning/angular/state-management/dist/server/playlist/playlist.controller.js:116:16)
    at /Users/mark.mccracken/Work/learning/angular/state-management/node_modules/@nestjs/core/router/router-proxy.js:7:33
    at Layer.handle [as handle_request] (/Users/mark.mccracken/Work/learning/angular/state-management/node_modules/@nestjs/core/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/mark.mccracken/Work/learning/angular/state-management/node_modules/@nestjs/core/node_modules/express/lib/router/route.js:131:13)
::1 - - [02/Aug/2017:21:14:37 +0000] "GET /api/playlist HTTP/1.1" 500 31
```

Hope this might help anyone coming behind me with a really simple solution

**Comment by carloscasalar** [comment]
> This will only work so long as your typescript's tsconfig.json is targeting es2015 or higher, if targeting es5, this will throw an error like so...

This is happening to me also with ES6 in tsconfig.json.

**Comment by ShacharHarshuv** [comment]
When it was said that this framework works in TypeScript I expected it to support express types integrally. For example - I don't need to import the express module because NestJS does that for me. Why than would I need to import express types? The types should be imported and inferred automatically when I use the @Req decorator.

**Comment by ShacharHarshuv** [comment]
What if I'll just need to write the type (e.g. Request) without a decorator and Nest will give me the request like happens with dependency injection? (You ask for a class and the injector supplies you with an instant.)
Is that something that might be possible to implement?

**Comment by marcus-sa** [comment]
Then the package would still need to have both Fastify and Nest platform installed for it to work, and Nest still supports JS, so that's not an option either, plus it's more a downgrade than an actual bug fix imo

**Comment by ThenmozhiGit** [comment]
Any update on this? I still face the same issue when targeting es2017.  Using Nest 6.5.3
