### ISSUE TITLE
WebSocket init options for SocketIO

### ISSUE THREAD

**Issue by Progdom** [kamilmysliwiec/nest#121]
Currently, there is no way to configure the initialization options of a socketIO server. You have to create an adapter and bind handlers which seems like a lot of work when you there could be a way to do this possibly in the WebSocketGateway decorator? If not there, possibly the WebSocketServer decorator. Something to the effect of 
``` javascript
     @WebSocketGateway({
               options: {
                  //init options for server
               }
    })
 ```
or 

``` javascript
      @@WebSocketServer({
               options: {
                  //init options for server
               }
    })
 ```

**Comment by kamilmysliwiec** [comment]
Hi @Progdom,
It's necessary to create an adapter, but I don't think it's a lot of work now. You can just extend the default one and overload the existing methods :smiley: 
Thanks, Kamil

**Comment by ericzon** [comment]
@Progdom on v5 beta 3 we have more options to pass to the gateway :grin: 

```
{
    namespace?: string;
    path?: string;
    serveClient?: boolean;
    adapter?: any;
    origins?: string;
    parser?: any;
    pingTimeout?: number;
    pingInterval?: number;
    transports?: string[];
}
```
