### ISSUE TITLE
Trigger Pipes with GET requests too

### ISSUE THREAD

**Issue by ericzon** [kamilmysliwiec/nest#129]
We've been trying pipes to validate inputs as doc explains and it works fairly well with post requests, but it doesn't seems to work for every typical crud verbs. It would be nice to use the same kind of component for validation in every place.

Currently using:

common: "version": "3.0.0"
core: "version": "3.0.1"
microservices: "version": "3.0.1"
testing: "version": "3.0.0"
websockets: "version": "3.0.0"

Thanks

**Comment by kamilmysliwiec** [comment]
Hi @ericzon,
Everything should work fine since v4 release.
Thanks, Kamil
