### ISSUE TITLE
Any plans for implementing advrnced features 

### ISSUE THREAD

**Issue by vlio20** [kamilmysliwiec/nest#130]
Hi, 
I really love the concept this framework is taking, I am curious if you plan to implement more advanced features. 

When I say advanced features I am talking about features that are existing in a framework like Laravel. For example, caching email sending, template engine, throttling, configuration per environment etc. 

If so, I would like to contribute and implement some of this features. Let me know wdyt. 

Please continue with the awesome work!

**Comment by kamilmysliwiec** [comment]
Hi @vlio20,
This framework solves the architectural issues. The Nest idea is not to provide the ready-to-use common solutions :cat: 
Thanks! Kamil

**Comment by chriszrc** [comment]
At a minimum, it would be nice to support different environments (just like angular cli does right out of the box), with at least a default environment and a prod. Or maybe at least add environment configuration to the documentation or maybe just to the nestjs-cli?

**Comment by ThomRick** [comment]
Hey @chriszrc !
The build command is not developed yet in nest-cli but it is in the development pipe.
Currently nest-cli needs some refactoring to be ready for the next feature developments like build, lint...
I'll give soon the trello of next feature developments according to @kamilmysliwiec requirements about Nest evolutions and feedbacks ;-)

**Comment by chriszrc** [comment]
I think this makes a lot of sense, practically every project I've ever worked on had to have environment specific configuration, and it was really the only glaring omission from the stock nestjs starter seed / documentation. I ended up following the environment config example from here:

https://github.com/d3viant0ne/nestjs-mongoose/blob/master/src/shared/environments.ts
https://github.com/d3viant0ne/nestjs-mongoose/blob/master/src/app/app.bootstrap.ts

Creating some kind of app component/bootstrap seemed a pretty sensible way to approach this-

**Comment by williamchristophercooley** [comment]
yeah on enterprise products you are always pointing to different databases, micro services, and etc.. it's a highly needed feature.

**Comment by cojack** [comment]
> At a minimum, it would be nice to support different environments (just like angular cli does right out of the box), with at least a default environment and a prod. Or maybe at least add environment configuration to the documentation or maybe just to the nestjs-cli?

Easy to solve, check @chriszrc mine solution: https://github.com/cojack/ts-config

**Comment by chriszrc** [comment]
Hi, oh, I solved this, no problem, it's just that I was annoyed I had to solve it manually, rather than being provided out of the box. I think I initially followed the setup of one of the nestjs contributors - https://github.com/d3viant0ne/nestjs-mongoose

**Comment by zuohuadong** [comment]
@vlio20  We are trying to do such a thing.
