### ISSUE TITLE
[Question] Exception filter object with dependencies

### ISSUE THREAD

**Issue by ddyrcz** [kamilmysliwiec/nest#131]
I need to create **global** expection filter object (`ApplicationExceptionFilter`) that **depends** on the `Logger` component that is part of the `ApplicationModule`

**Application module:**

``` typescript
@Module({
  components: [
    Logger
  ]
})
export default class ApplicationModule { }
```

**Logger:**
``` typescript

@Component()
export class Logger {
  log(message : string) {
    // log somewhere
  }
}
```

**Expection filter:**
``` typescript

@Catch(Error)
export class ApplicationExceptionFilter implements ExceptionFilter {
  constructor(private logger : Logger) { }

  catch(exception: Error, response: Response) {
    this.logger.log('some message')
    response.status(500).end()
  }
}
```

 Currently I create dependencies manually (I have 2 instances of an logger)

``` typescript
app.useGlobalFilters(new ApplicationExceptionFilter(new Logger()))
```

Is  it possible to retrieve `Logger` instance from the `ApplicationModule ` and pass it to the `ApplicationExceptionFilter` ?

Or is there a better solution for `ExceptionFilter` objects' dependencies management?

**Comment by kamilmysliwiec** [comment]
Hi @ddyrcz,
The exception filters are detached from the modules scopes. The interceptors should fit the gap in your problem. http://www.docs.nestjs.com/interceptors :cat:
Thanks, Kamil

**Comment by Yerkon** [comment]
@kamilmysliwiec, in [exception-filters](https://docs.nestjs.com/exception-filters) article => Global filters 
chapter is written: 

> Let's assume that we have a  **LoggerExceptionFilter** registered in the  **LoggerModule**. This  LoggerModule is imported into the root module

You say:

> The exception filters are detached from the modules scopes. The interceptors should fit the gap in your problem. http://www.docs.nestjs.com/interceptors 🐱


So, it means this docs should be updated?

**Comment by Yerkon** [comment]
Also in docs, will be good to add chapter navigation like in angular.io like https://angular.io/guide/architecture#modules

**Comment by IsraelZablianov** [comment]
Hi @ddyrcz, @kamilmysliwiec 

There is another thing you can do.
import `ApplicationExceptionFilter` in `ApplicationModule` as provider, and export it.
It will make `ApplicationExceptionFilter` injectable with token.

the last thing is to use it in your `main` file:
```ts
...
      app.useGlobalFilters(app.get(ApplicationExceptionFilter))
...
```

**Comment by finchen** [comment]
```js
...
      app.useGlobalFilters(app.get(ApplicationExceptionFilter))
...
```
It is working as long as ApplicationExceptionFilter does not depend on scope request provider. (trying to assign a request id on the log/error)
It is the same issue with an interceptors.
I think I have to use the `HttpAdapterHost`
