### ISSUE TITLE
[Question] Any seed for SSR?

### ISSUE THREAD

**Issue by juan-manuel-alberro** [kamilmysliwiec/nest#132]
Hello, I'm using Nest with Pug (Jade) I want to know if there's any seed / boilerplate for server side rendering (SSR), something for Angular, React or Vue.

Thanks!

**Comment by cdiaz** [comment]
Hi, Try use [Nest with Nuxt](https://github.com/AngelMunoz/nesting-nuxt)  by [ Angel Munoz](https://github.com/AngelMunoz)

**Comment by AngelMunoz** [comment]
yeah I had a bit of troubles with that as asked in #119 but no response so far and haven't had time to work on it however if you guys could made it work It would be nice to know!

**Comment by juan-manuel-alberro** [comment]
Hello @AngelMunoz, I tried last night and it seems that the /api/* calls aren't working, besides that seems to be working fine. Maybe @kamilmysliwiec can help you in #119 😄 
Thanks to all!

**Comment by AngelMunoz** [comment]
@juan-manuel-alberro hey someone found an answer/workaround to #119 so you could take it on a spin again cloning from master the nest-nuxt integration is just working fine

**Comment by juan-manuel-alberro** [comment]
Lovely! thanks for the heads up @AngelMunoz!

**Comment by kamilmysliwiec** [comment]
Thanks @AngelMunoz. Closing :cat:
