### ISSUE TITLE
Implementation of DirectEvents or similar

### ISSUE THREAD

**Issue by juliandavidmr** [kamilmysliwiec/nest#133]
Hello, I have been programming in .NET for a long time. I love everything about nodejs but I've noticed that something is missing. There is a type of events that I have only seen in the aspx template engine (asp.net), this engine allows something called DirectEvents, 
[DirectEvents](https://www.packtpub.com/mapt/book/web_development/9781849693240/4/ch04lvl1sec34/directevents) are server-side event handlers for events triggered on the client side. [Meteor.js](https://www.meteor.com) implements something similar along with its [Blaze](http://blazejs.org) engine.

Is there any possibility that nest will integrate with the Blaze engine?
_Or even better, what do you think about the idea of creating your own for nest?_

**Comment by c0d3x42** [comment]
@juliandavidmr have you looked at Socket.IO in Nest? That sounds very much like what you are talking about.

**Comment by juliandavidmr** [comment]
Hi @c0d3x42, I think that with Socket.IO it could be, but so far everything must be done manually,
Instead with blaze everything is done automatically.

**Comment by kamilmysliwiec** [comment]
Hi @juliandavidmr,
The Nest is trying to provide the architecture, not ready-to-use solutions such as described events, so there's no plan to introduce this in the future. :cat: 
Kamil
