### ISSUE TITLE
Question about WebSocketGateway class - Emit to channel from external component

### ISSUE THREAD

**Issue by jgordor** [kamilmysliwiec/nest#134]
Hi,

I have a simple WebSocketGateway:
```ts
import { WebSocketGateway, SubscribeMessage } from '@nestjs/websockets';

@WebSocketGateway({ port: 3001, namespace: 'ws' })
export class TestGateway {
  @SubscribeMessage('channel-1')
  onMessage(client, data) {
    client.emit('channel-1', data);
  }
}
```

I'm trying to send messages (broadcast) to this channel from other parts of the application (others components that can be or not inside the same module). 

There is a way to do it without connecting via a socket.io client?

Thanks

**Comment by jgordor** [comment]
Solved it using:
```ts
  @WebSocketServer() 
  private server: any;
```

So I can:
```ts
this.server.emit('channel-1', 'Hey!');
```

**Comment by ahmadarif** [comment]
Any idea to emit from controller?

**Comment by Mangdar** [comment]
Any idea to emit from controller?

**Comment by FilipeMazzon** [comment]
> Any idea to emit from controller?

in controller you will call the function on the gateway example:

  @MessagePattern({ cmd: 'broadcast_all' })
  async broadcastAll(data: exampleDTO) {
    return await this.exampleGateway.brodcastAll(data);
  }

and in gateway:
@WebSocketServer() server;
 async brodcastAll(data) {
    try {
      this.server.emit('example_event', data);
    } catch (e) {
      //handle error here
    }
  }
