### ISSUE TITLE
Apply middleware to all routes

### ISSUE THREAD

**Issue by ddyrcz** [kamilmysliwiec/nest#135]
Is it possible to use `middleware` function for all routes?

In [express.js](https://expressjs.com/) you can quickly achieve this by applying function to the application's use method:

``` javascript
app.use(function (req, res, next) {
 // do whatever you like
  next();
});
```

**Comment by adrien2p** [comment]
Hey ! yes of course,
in the `*.module.ts` you can add the following things
```ts
export class UsersModule {
    configure(consumer: MiddlewaresConsumer) {
            consumer.apply(AuthMiddleware).forRoutes(YourController);
    }
}
```

that apply the middleware for all routes in the controller.

**Comment by ddyrcz** [comment]
_that apply the middleware for all routes **in the controller**._

You need to **list the controllers** that you want to apply middleware function (if you will add a new controller it need to be added to that list)

But is there a way to apply middleware function on all the routes of every controller?

**Comment by adrien2p** [comment]
Ok sorry for the miss understanding, in this case you can use `instance.all('*', YourMiddleWare)`
That's apply it on all incoming route path whatever the method used(GET, POST, PUT, ...)
```ts
const instance = express();
instance.all('*', MiddleWare);
const app = NestFactory.create(ApplicationModule, instance);
```

**Comment by ddyrcz** [comment]
So as I can see it can be achieved using `express instance` **outside** nest app

thanks @adrien2p

**Comment by ddyrcz** [comment]
@adrien2p 

I have not noticed this in the documentation. You can also achieve this by defining the path for which the middleware function should by applied like this:

``` typescript
consumer.apply(AuthMiddleware).forRoutes({ 
    path: '*', method: RequestMethod.ALL 
});
```

**Comment by adrien2p** [comment]
Yes you can do this  but i dont know if it's apply in all route app

**Comment by ddyrcz** [comment]
I have configured it in the application module

``` typescript
@Module({
  modules: [
    CategoryModule,
    AuthModule
  ]
})
export default class ApplicationModule {
  configure(consumer: MiddlewaresConsumer) {
    consumer.apply(AuthMiddleware)
      .forRoutes({
        path: '*', method: RequestMethod.ALL
      });
  }
}
```

And it applies middleware function to **all** routes in the application

**Comment by adammfrank** [comment]
Is it possible to run middleware for all routes except for one? For example, I want to run authorization on all routes except for the one that handles the initial authentication request.

**Comment by cdiaz** [comment]
@adammfrank  this same was recommended in #17 since April
[check this](https://github.com/nestjs/nest/issues/17#issuecomment-294633298), I think it's very useful

**Comment by riadhriadh** [comment]
public resolve() {
    return async (req, res, next) => {
        if (req.headers.authorization ){
            const token = req.headers.authorization;
            const decoded: any =passport.authenticate(token, process.env.JWT_KEY || '');
           console.log(decoded)
         
    };
    next();
}
}

**Comment by riadhriadh** [comment]
` public resolve() {
    return async (req, res, next) => {
        if (req.headers.authorization ){
            const token = req.headers.authorization;
            const decoded: any =passport.authenticate(token, process.env.JWT_KEY || '');
           console.log(decoded)
         
    };
    next();
}`
