### ISSUE TITLE
Add request methods HEAD, OPTIONS

### ISSUE THREAD

**Issue by oscaroox** [kamilmysliwiec/nest#138]

**Comment by adrien2p** [comment]
Whay do you mean ? What you do you want to do ?

**Comment by oscaroox** [comment]
@adrien2p Its possible to use the post,put,patch,delete,get methods but not head and options

```

**Comment by adrien2p** [comment]
Do you want set header ?

**Comment by oscaroox** [comment]
something like this 
```js
import {Controller, Head} from '@nextjs/common'
import userService from './user.service'

@Controller()
class UserController {

  // using proper http verb to check if resource exists
  @Head('/auth/:username')
  async userExists (req, res) {
    let exists = await userService.exists(req.params.username)

    if (!exists) {
       res.status(200)
    } else {
       res.status(404)
    } 

    res.send()
  }
}

```

**Comment by adrien2p** [comment]
Hum yeah you right it's nit implemented yet may be in the v4

**Comment by sabakugaara** [comment]
OPTIONS is used by cors preflighted: https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS#Preflighted_requests

should be supported

**Comment by kamilmysliwiec** [comment]
Hi @oscaroox,
Both `@Head()` and `@Options()` should be available since v4 release.
Thanks, Kamil

**Comment by kamilmysliwiec** [comment]
@ShinDarth you never have to do it actually
