### ISSUE TITLE
Why 'Component' is not named 'Service'?

### ISSUE THREAD

**Issue by zD98** [kamilmysliwiec/nest#139]
I see the document. And  `Nest` use `Component` to describe `Service`. Why not just use `Service`

**Comment by JulianBiermann** [comment]
I guess that Nest ist not forcing you to have a typical `Controller -> Service` structure in your project. You could define other Classes which are `Components` of the application but not `Services`.

In our project we're using a repository layer which also needs to be decorated with the `Component` decorator.

**Comment by kamilmysliwiec** [comment]
Hi @zD98,
@JulianBiermann describes the idea very well. Not every `Component` is a `Service`. I didn't want to create the aliases such as `@Service` or `@Repository`. If you want - you can do this in your project without any effort :smiley: 
Thanks, Kamil
