### ISSUE TITLE
[Documentation] Incorrect method name in the middlewares example

### ISSUE THREAD

**Issue by alexcorvi** [kamilmysliwiec/nest#14]
In [this page](https://kamilmysliwiec.gitbooks.io/nest/content/quick-start/middlewares.html) You're referencing a method name `getUsers`, unfortunately this method does not exist in the users service. Instead You should have used `getAllUsers`.

Again, I know it's just an example for demonstration purposes, but nevertheless it should work.

Another question: is there a way to contribute to the documentation? It can be a tedious task for you to do alone, I'll be happy to help in anyway!

**Comment by kamilmysliwiec** [comment]
Hi @alexcorvi again,
Many thanks! Now it should works fine.

If I remember properly, there is something like change requests in gitbook, so you can use it. It would be very helpful :)!

**Comment by kamilmysliwiec** [comment]
**Update:**
This method has been correct ;) You have to scroll down:
```
Notice: I added getUsers method to UsersService, which returns encapsulated list of stored users.
```

`getAllUsers()` returns promise, not just an array.

**Comment by alexcorvi** [comment]
Oh I see!
