### ISSUE TITLE
[Feature, Question] Method level @Cache annotation

### ISSUE THREAD

**Issue by rychkog** [kamilmysliwiec/nest#140]
Want to implement one, but the only way to access Request, Response - via middlewares, which are outside of the controller. Is it possible using the current (3.x) version of Nest?

```typescript
import { Controller, Get, Post, HttpStatus } from '@nestjs/common';

@Controller()
export class UsersController {
    @Cache({period: '1m', key: (req, res) => req.originalUrl})
    @Get('users')
    getAllUsers() {}
}
```

**Comment by kamilmysliwiec** [comment]
Hi @rychkog,
I think the interceptors & custom decorators feature will fit great here.
http://www.docs.nestjs.com/interceptors
Best, Kamil

**Comment by chriszrc** [comment]
Could we use something like this out of the box at least on the service methods?

https://www.npmjs.com/package/node-ts-cache

(Also, is there a better one out there already, or is this the place to start?)

**Comment by xmlking** [comment]
implemented a prototype here 
https://github.com/nestjs/nest/issues/1032
