### ISSUE TITLE
[Feature] Swagger support？

### ISSUE THREAD

**Issue by NeroCho** [kamilmysliwiec/nest#141]
Is there a plan to support apidoc? 
eg: https://github.com/thiagobustamante/typescript-rest-swagger

**Comment by d3viant0ne** [comment]
It's coming in the v4 release

**Comment by kamilmysliwiec** [comment]
Hi @NeroCho,
The swagger module is in @beta version, need some time to publish & describe :)
Duplicated - https://github.com/kamilmysliwiec/nest/issues/67
Best,
Kamil
