### ISSUE TITLE
Exception filters module-scoped

### ISSUE THREAD

**Issue by Lukinoh** [kamilmysliwiec/nest#144]
Hi, 

Thank you for your amazing work. I just have a question. Is it possible to do exception filters that are module-scoped ? If not, there is some kind of limitations that make this impossible ?

Best regards

**Comment by kamilmysliwiec** [comment]
Hi @Lukinoh,
It's not possible, but I believe it's not really necessary since module should contain max 2-3 controllers :smiley: 
Best, Kamil
