### ISSUE TITLE
tsc error

### ISSUE THREAD

**Issue by afgallo** [kamilmysliwiec/nest#2]
Hi @kamilmysliwiec ! Thanks for your framework, it looks very promising!

I just wanted to report this error with typescript typings. When I run tsc from the command line with the following tsconfig.json configuration I get the error below:

`node_modules/nest.js/nest-factory.d.ts(10,63): error TS2304: Cannot find name 'NestApplication'.`

```
{
    "compilerOptions": {
        "module": "commonjs",
        "declaration": false,
        "noImplicitAny": false,
        "removeComments": true,
        "noLib": false,
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "target": "es6",
        "sourceMap": true,
        "allowJs": true,
        "outDir": "./dist"
    },
    "include": [
        "app/**/*"
    ],
    "exclude": [
        "node_modules",
        "**/*.spec.ts"
    ]
}
```

**Comment by kamilmysliwiec** [comment]
Hi @afgallo,

Thanks for your kind words. According to the issue - good point.  I already repaired this bug, please - just update nest package. It should helps.

**Comment by afgallo** [comment]
Cool. Nice work @kamilmysliwiec, it works now.
