### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by Mark-McCracken** [kamilmysliwiec/nest#23]
Compiling the project results in
<img width="655" alt="screen shot 2017-05-04 at 20 31 17" src="https://cloud.githubusercontent.com/assets/14816091/25721536/b1c9df64-3108-11e7-9215-d2cdcb90a7e8.png">
this error.

This seems to stem from the ```express_1.default();``` line. Removing ```.default``` seems to resolve this issue.

Here's my tsconfig for reference
tsconfig.json
```js
{
  "compilerOptions": {
    "baseUrl": "",
    "module": "commonjs",
    "mapRoot": "./",
    "outDir": "../server-dist",
    "declaration": false,
    "noImplicitAny": false,
    "noLib": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": ["es2016"],
    "target": "es6",
    "sourceMap": true,
    "allowJs": true
  },
  "exclude": [
    "node_modules"
  ]
}
```

**Comment by Pinedo11** [comment]
Hey!
Bearing in mind that you have followed the official documentation try this:

In index.ts change:
`import express from 'express';`
for: 
`import * as express from 'express';`.

**Comment by Mark-McCracken** [comment]
That works!
Thanks!
