### ISSUE TITLE
WebSocket adapters

### ISSUE THREAD

**Issue by ProbablePrime** [kamilmysliwiec/nest#29]
It would be great to extract the websocket functionality to use a proper adapter pattern.

Right now there's a stub of [an adapter](https://github.com/kamilmysliwiec/nest/blob/master/src/websockets/adapters/io-adapter.ts) which just returns a socket.io instance.

Ideally:
- Wrap any websocket functionality in an adapter
- Call that in nest side code

This lets socket.io be potentially swapped out for alternatives, without breaking changes.

**Comment by hustcer** [comment]
[uWebSockets](https://github.com/uWebSockets/uWebSockets) should be better than socket.io, IMO

**Comment by d3viant0ne** [comment]
Socket.io is familiar to most of the Angular community of which Nest has it's roots. I don't disagree that uWebSockets outperforms socket.io at scale but imo Nest shouldn't make choices like that for consumers.

As @ProbablePrime said above, make it pluggable, support what makes sense & allow consumers to make their own tooling choices.

**Comment by kamilmysliwiec** [comment]
Hi @ProbablePrime,
Since latest update you should be able to use custom socket.io adapter. Example:

```typescript
import { SocketIoAdapter } from '@nestjs/common';

class CustomAdapter implements SocketIoAdapter {
    create(port: number) {
        return {};
    }
    createWithNamespace(port: number, namespace: string) {
        return {};
    }
}

const app = NestFactory.create(ApplicationModule, instance);
app.setIoAdapter(new CustomAdapter());
```

**Comment by ProbablePrime** [comment]
@kamilmysliwiec I don't think this addresses the issue.

The issue is asking for a way to replace Socket.io completely. Right now this appears to just require an adapter to return Socket.io instances.

**Comment by cojack** [comment]
@kamilmysliwiec will be this #80 pr merged in a few days?

**Comment by kamilmysliwiec** [comment]
@cojack, yes

**Comment by ProbablePrime** [comment]
This looks a lot better \o/ thanks! doing a more indepth read of your changes but i will close it most likely

**Comment by kamilmysliwiec** [comment]
Hi @ProbablePrime,

Since `3.0.0` you can create adapter for any ws library. [Read more](https://docs.nestjs.com/quick-start/adapters.html)

**Comment by ProbablePrime** [comment]
Yep PERFECT. thanks!
