### ISSUE TITLE
Suggestion: ORM integration

### ISSUE THREAD

**Issue by KerryRitter** [kamilmysliwiec/nest#31]
Many frameworks have a preferred ORM integrated out of the box (ASP.NET with Entity Framework, Laravel with Eloquent, Sails with Waterline). Perhaps Nest should consider doing this as well? TypeORM seems to be picking up steam and perhaps could be a candidate https://github.com/typeorm/typeorm.

**Comment by NoNameProvided** [comment]
There is an ongoing discussion about this in [#6 Future of the framework, contributions, evangelism](https://github.com/kamilmysliwiec/nest/issues/6#issuecomment-299434129).

**Comment by KerryRitter** [comment]
Whoops! Sorry about that. Closing.
