### ISSUE TITLE
Testing component with Jest

### ISSUE THREAD

**Issue by jakub-gawlas** [kamilmysliwiec/nest#35]
Hello everyone 😃 

I was tried to testing my simple component with using Jest, but something was go wrong.

Configured Jest to working with TypeScript according to [official example](https://github.com/facebook/jest/tree/master/examples/typescript) and `tsconfig` copied from Nest repo.

The simplest tested component:
```js
import { Component } from 'nest.js';

@Component()
export class TestService {}
```
Test for the one:
```js
import { TestService } from '../test.service';

it('should create instance', () => {
  const instance = new TestService();
})
```

Unfortunately result of run test is:
```bash
  ● Test suite failed to run

    Cannot find module 'socket.io-client/package' from 'index.js'

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:169:17)
      at Object.<anonymous> (node_modules/socket.io/lib/index.js:10:21)
```

What am I doing wrong? Maybe someone has already tested Nest with Jest?

Cheers! :clinking_glasses:

**Comment by ThomRick** [comment]
Hey @jakub-gawlas,

I tried to reproduce your issue but can not... 
I have the same test sample as you:
```typescript
import {UserService} from './user.service';

it('should create instance', () => {
  const instance = new UserService();
});
```
And the following test report:
```text
 PASS  src/app/services/user.service.test.ts
  ✓ should create instance (1ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        1.685s
Ran all test suites.
```
Did you update your package.json as indicates in Jest  documentation to use typescript ?
```json
{
  "name": "nest.js-tutorial",
  "version": "1.0.3",
  "description": "An implmentation tutorial about NestJS",
  "main": "main.js",
  "scripts": {
    "build": "tsc",
    "start": "node dist/main.js",
    "test": "jest"
  },
  "author": "ThomRick",
  "license": "ISC",
  "dependencies": {
    "body-parser": "^1.17.1",
    "nest.js": "1.0.3"
  },
  "devDependencies": {
    "@types/express": "^4.0.35",
    "@types/jest": "^19.2.3",
    "@types/node": "^7.0.11",
    "jest": "^19.0.2",
    "ts-jest": "^19.0.14",
    "typescript": "^2.2.1"
  },
  "jest": {
    "transform": {
      "^.+\\.tsx?$": "<rootDir>/node_modules/ts-jest/preprocessor.js"
    },
    "testRegex": "(/__tests__/.*|\\.(test|spec))\\.(ts|tsx|js)$",
    "moduleFileExtensions": [
      "ts",
      "tsx",
      "js",
      "json"
    ]
  }
}
```
An other question: Which version of NodeJS do you use ?

**Comment by jakub-gawlas** [comment]
@ThomRick thanks a lot! Error was caused by lack of `json` extension in `moduleFileExtensions`. In Jest example the one isn't present, why is needed in this case?

**Comment by ThomRick** [comment]
Hey @jakub-gawlas,

I don't know exactly why it's needed but I've looked about ts-jest documentation here:

https://www.npmjs.com/package/ts-jest

And this section may be the cause:
```text
Known limitations for TS compiler options
You can't use "target": "ES6" while using node v4 in your test environment;
You can't use "jsx": "preserve" for now (see progress of this issue);
If you use "baseUrl": "<path_to_your_sources>", you also have to change jest config a little bit:
"jest": {
  "moduleDirectories": ["node_modules", "<path_to_your_sources>"]
}
```
There is no clear explanations about the configuration sections.
If you can have more information don't hesitate to share ;-)
