### ISSUE TITLE
Problem with express typing

### ISSUE THREAD

**Issue by mgween** [kamilmysliwiec/nest#36]
Following along with the Setup Application instructions, when I add express I get the error upon typescript compilation: 
`node_modules/nest.js/core/middlewares/interfaces/nest-middleware.interface.d.ts(1,1): error TS2688: Cannot find type definition file for 'express'.`

I used `npm install --save-dev @types/express` to add the typing and now I get the error:
`index.ts(1,8): error TS1192: Module '"C:/Users/Matt/dev/tests/nest-test/node_modules/@types/express/index"' has no default export.`

**Comment by ScottMGerstl** [comment]
Same issue. I tried looking at the example in the repo. but there are imports from all over.

**Comment by kamilmysliwiec** [comment]
Hi @mgween, @ScottMGerstl 

You're right. Thanks for reporting. Please, update your packages into `1.0.4` version.

**Comment by mgween** [comment]
Thanks so much.
