### ISSUE TITLE
Incompatible with reflect-metadata release 0.1.10+

### ISSUE THREAD

**Issue by zachgrayio** [kamilmysliwiec/nest#37]
If running reflect-metadata 0.1.10+, decorated components and modules don't seem to be picked up and routes aren't generated correctly.

**Comment by kamilmysliwiec** [comment]
Hi @zachgrayio,
I can't reproduce your issue. Could you specify what exactly doesn't work? The source code also will be useful :)
Thanks

**Comment by zachgrayio** [comment]
I'll upload an example later if needed, but this is the important piece for reproduction in Nest 1.0.3 with reflect-metadata 0.1.10:

Add `import "reflect-metadata";` in the top of your app or server.ts before Nest initialization (as directed in Installation Step 2 here: https://github.com/typeorm/typeorm) 

This results in a Nest app which boots without crashing, but the output is:
[Nest] 35027   - 5/6/2017, 3:23:42 PM   [NestFactory] Starting Nest application...
[Nest] 35027   - 5/6/2017, 3:23:42 PM   [InstanceLoader] ApplicationModule dependencies initialized
[Nest] 35027   - 5/6/2017, 3:23:42 PM   [NestApplication] Nest application is ready!

... when there should be additional output for module/controller generation. And inspecting the underlying express object shows that indeed no routes were created.

**Comment by zachgrayio** [comment]
I forked the starter repo and added your example code to it here, and also included the reflect-metadata import statement and explicitly added the 0.1.9 dependency to demonstrate that it still works: 
https://github.com/zachgrayio/nest-typescript-starter/tree/example

**Comment by kamilmysliwiec** [comment]
Hi @zachgrayio,
Thanks. It looks that 0.1.9 is not fully compatible with latest version. I updated the reflect-metadata dependency into 0.1.10 version within Nest package and issue disappeared. Please, install `1.0.5` version of Nest.

**Comment by zachgrayio** [comment]
Cool, looks good.
