### ISSUE TITLE
Auth0 Example

### ISSUE THREAD

**Issue by gsogol** [kamilmysliwiec/nest#38]
Looking for an auth0 example since it's defacto authentication platform nowadays

**Comment by cdiaz** [comment]
I've an [basic example](https://github.com/cdiaz/nestjs-auth0.git) of authentication using Auth0, I still do not have a solid architecture and can improve, but I hope it will guide you.

Preview:
![](https://media.giphy.com/media/3o7btM9aGAzX6iYBji/giphy.gif)

**Comment by alexjoverm** [comment]
Just for tracking, it was mention on #6 to have an examples showcase section. This could be included there as well. We can close this.

**Comment by gsogol** [comment]
Thanks @cdiaz

**Comment by jajaperson** [comment]
@cdiaz provides a web application example, but what about an API example?

**Comment by blee-smcoe** [comment]
There's an API example from auth0 https://auth0.com/blog/full-stack-typescript-apps-part-1-developing-backend-apis-with-nestjs/
It's just really out of date.

**Comment by jajaperson** [comment]
I actually ended up making an example myself: <https://github.com/jajaperson/nest-auth0>

**Comment by blee-smcoe** [comment]
Thanks @jajaperson I found it 2 days ago once I started searching for 'nest auth0' instead of 'nestjs auth0'
