### ISSUE TITLE
Can I help you by contributing ?

### ISSUE THREAD

**Issue by ThomRick** [kamilmysliwiec/nest#4]
Hello,

First of all congrats for the initiative !
I'm very enthusiastic about the project and I'd like to help you by contributing.
I cloned the repository and I started to fix sinon warnings in the unit tests.

Tell me if you need ! ;-)

**Comment by juandav** [comment]
The project is cool.

**Comment by kamilmysliwiec** [comment]
Thanks guys! I appreciate each help. If you have any ideas, please share them with me. There is not a lot of to do right now, but it will probably change in the future ;)
