### ISSUE TITLE
Global route for all controllers

### ISSUE THREAD

**Issue by jezikk** [kamilmysliwiec/nest#40]
Hi,

is there any suggested way how to set a "global" route for all controllers?

For example, I want to define this route:
`/api/`

for my controllers:

```
@Controller('user')
export class UserController

@Controller('customer')
export class CustomerController
```

with the following result:

```
/api/user
/api/customer
```

Thank you

**Comment by alexjoverm** [comment]
I was wondering about the same. In [express](http://expressjs.com/en/guide/routing.html#express-router) you can prepend paths by using the Router, and then:

```javascript
app.use('/a-route', aModule)
```

Is this existing in nest, or is a feature request?

**Comment by cojack** [comment]
@jezikk or combine it with https://github.com/pleerock/routing-controllers

**Comment by alexjoverm** [comment]
Very interesting, that library allows both global prefixes and per-controller prefixes, such as:


```typescript
@Controller("/users")
export class UserController {
    // ...
}
```

**Comment by kamilmysliwiec** [comment]
Hi @jezikk,
Since version `2.1.0` you can use `setGlobalPrefix(prefix: string)` method. Example:

```typescript
const app = NestFactory.create(ApplicationModule);
app.setGlobalPrefix('api');
```

**Comment by sferhan** [comment]
Hi! I am trying to use the setGlobalPrefix function but it isn't working.

const app = await NestFactory.create(AppModule);
app.setGlobalPrefix('api');
  app.useGlobalFilters(new CustomExceptionFilter());
  app.useGlobalInterceptors(new ResponseInterceptor());
  await app.listen(3000);

My package.json dependencies include
"@nestjs/common": "^5.0.1",
    "@nestjs/core": "^5.0.1",
    "@nestjs/microservices": "^5.0.1",
    "@nestjs/passport": "^1.0.11",
    "@nestjs/swagger": "^2.0.2",
    "@nestjs/testing": "^5.0.1",
    "@nestjs/typeorm": "^5.0.1",
    "@nestjs/websockets": "^5.0.1"

**Comment by flogvit** [comment]
Should this work with swagger?

`
const app = await NestFactory.create(AppModule);
app.setGlobalPrefix('v1');
const options = new DocumentBuilder()
      .setTitle('title')
      .setDescription('API description')
      .setVersion('0.1')
      .addTag('tag')
      .build();
  const document = SwaggerModule.createDocument(app, options);
  SwaggerModule.setup('docs', app, document);`

This doesn't add v1 as prefix in the documentation reflected on /docs/, but is reflected to the api, so I have to call /v1/... to get the endpoint.

Is this a bug?

**Comment by kgajowy** [comment]
@flogvit 
```
// document
    .setBasePath('v1')
```

As you can create multiple swagger documents (like, for every API version) it makes sense that it is no automatically derived from `app`

**Comment by vit100** [comment]
Not sure if there is solution, but in my case I need only prefix on specific controllers, not global.
So application should have following routes:
/ - root
/api/cat
/api/dogs

And path in @Controller('api/cats') or @Controller('api/dogs') doesn't work.
