### ISSUE TITLE
[Feature Request] RabbitMQ transport for Microservices

### ISSUE THREAD

**Issue by alexjoverm** [kamilmysliwiec/nest#44]
A message broker is one of the most used transport patterns in production microservices, being RabbitMQ the most popular of them.

It could be a great addition to Nest

**Comment by cdiaz** [comment]
We should also consider communication with MQTT, for the internet of things.

**Comment by ThomRick** [comment]
Hey guys,

I think that's some modules that could plugged to nest to be used.
I think that the framework should be have only core features (web architecture design only) and you can add others on demand shouldn't be ?
Like Spring you can add extra modules to solve specific cases

**Comment by alexjoverm** [comment]
Yes I think as a module would fit perfectly.

About that, how are modules gonna be organized in this repo? In different repos or the same one?

A good way others (like lodash, angular and more) are using is to keep everything in the same repo and use LernaJS for treating them as separate projects, producing different packages

**Comment by kamilmysliwiec** [comment]
Hi @alexjoverm,

Since `3.0.0` you can port any transport strategy to Nest. [Read more](https://docs.nestjs.com/real-time/microservices/custom-transport.html) (RabbitMQ as an example)
