### ISSUE TITLE
Make Logger service public available 

### ISSUE THREAD

**Issue by artaommahe** [kamilmysliwiec/nest#50]
To prevent additional loggers usages make existing Logger service public available.
Also extend declaration for `INestMicroservice` with `logger` field to allow `app.logger.log(...)` usage on startup instead of `console.log('Microservice is listening on port 3000'))` from examples.
Also made `logMessage` method public to print messages with custom colors.

**Comment by cojack** [comment]
```typescript
import { Module } from 'nest.js';
import { Logger } from 'nest.js/common/services/logger.service'

@Module({
    modules: []
})
export class ApplicationModule {
    private logger: Logger;

    constructor() {
        this.logger = new Logger(ApplicationModule.name);
        this.logger.log('Hello nest.js');
    }
}
```
@artaommahe you're welcome

**Comment by artaommahe** [comment]
@cojack i know how to import directly from sources, but this `nest.js/common/services/logger.service` is private, not public. Public is `import {  } from 'nest.js/common'`

**Comment by kamilmysliwiec** [comment]
Hi @artaommahe,
`Logger` is now a part of the public API (`@nestjs/common` package).
