### ISSUE TITLE
Mixed web and microservice app

### ISSUE THREAD

**Issue by artaommahe** [kamilmysliwiec/nest#52]
Can we have application type that is web app (handle http/websocket requests) and microservice (has tcp server that used by other microservices) at the same time? It's common;y used microservice type.

**Comment by kamilmysliwiec** [comment]
Hi @artaommahe,
Since version `2.1.0` you can easily create a hybrid, mixed web & microservice app.

```typescript
const app = NestFactory.create(ApplicationModule);
const microservice = app.connectMicroservice({
    transport: Transport.TCP,
    port: 5667,
});
```

You can run microservice directly:

```typescript
microservice.listen(() => console.log('Microservice is listening...'));
```

or using app `startAllMicroservices()` method:

```typescript
app.startAllMicroservices(() => console.log('All microservices are listening...'));
```

**Comment by artaommahe** [comment]
@kamilmysliwiec looks like this line is missed in npm version `2.1.0`
https://github.com/kamilmysliwiec/nest/blob/c7aaec5be079b741f94858a73e0ed0314887b69c/src/core/nest-application.ts#L54
in `nest-application.js` this method returns nothing

**Comment by kamilmysliwiec** [comment]
@artaommahe, thanks for fast feedback. Please, update your `@nestjs/core` into `2.1.1`.
