### ISSUE TITLE
Using Iterare instead of Array chain methods

### ISSUE THREAD

**Issue by cojack** [kamilmysliwiec/nest#55]
I would like to recommend [iterare](http://iterare.surge.sh/) for tranform a collection over using array chain methods. 
Regards.

**Comment by alexjoverm** [comment]
I don't understand this issue. Cannot one itself use iterate on its code? Is this issue meaning to use iterate in the core code of nest?

**Comment by cojack** [comment]
@alexjoverm fe:

from: instance-loader.ts
```
    private callModuleInitHook(module: Module) {
        const components = [...module.routes, ...module.components];
        components.map(([key, {instance}]) => instance)
                .filter((instance) => !isNil(instance))
                .filter(this.hasOnModuleInitHook)
                .forEach((instance) => (instance as OnModuleInit).onModuleInit());
    }
```
Depends on how many components are, this chain will be executed 4 times for N items.

So when we will use *iterare*:
```
    private callModuleInitHook(module: Module) {
        const components = [...module.routes, ...module.components];
        iterate(components).map(([key, {instance}]) => instance)
                .filter((instance) => !isNil(instance))
                .filter(this.hasOnModuleInitHook)
                .forEach((instance) => (instance as OnModuleInit).onModuleInit());
    }
```
Will only loop just once for N items. Slightly performance improvements. Bechmarks [http://iterare.surge.sh/#performance](http://iterare.surge.sh/#performance) shows the impact.

Regards.

**Comment by kamilmysliwiec** [comment]
Hi @cojack,
Since 2.0.0 version iterate library is used. Thanks for your proposal :)
