### ISSUE TITLE
Parametrizable middleware

### ISSUE THREAD

**Issue by AurelieV** [kamilmysliwiec/nest#61]
In my express applications, I often define a role check middleware factory. 
It takes a role array as a parameter, so I can reuse it for different roles checking (admin, moderator, etc) without rewrite a specific middleware for each case.

Is it possible to do something similar with Nest middlewares?

**Comment by kamilmysliwiec** [comment]
Hi @AurelieV,
You can use `MiddlewaresConsumer`.

```typescript
export class UsersModule implements NestModule {
    configure(consumer: MiddlewaresConsumer) {
        consumer.apply(AuthMiddleware).with(['admin', 'user']).forRoutes(UsersController);
    }
}
```

Then in the middleware:

```typescript
resolve(roles: string[]) {
    return (req, res, next) => {
        ///
        next();
    };
}
```

**Comment by AurelieV** [comment]
Thanks, I was searching this on the docs :)
