### ISSUE TITLE
Community question: Development environment

### ISSUE THREAD

**Issue by KerryRitter** [kamilmysliwiec/nest#65]
What is everyone using for their development environment? Has anyone successfully gotten interactive server-side debugging working with Nest or TypeScript-compiled tools?

**Comment by ThomRick** [comment]
Hey @KerryRitter,

Personally I use:
- Webstorm
- Typescript
- Jest as unit test framework
- No special debuging tools ==> just unit tests and logger

**Comment by JulianBiermann** [comment]
I'm using VS code and webpack to transpile and bundle my application.
Debugging also works fine in VS Code.

**Comment by kamilmysliwiec** [comment]
VS Code

**Comment by kamilmysliwiec** [comment]
@KerryRitter, do you need more answers or I can close this issue?

**Comment by silvelo** [comment]
@JulianBiermann How do you do to compile with Webpack? Can you post an example?

**Comment by JulianBiermann** [comment]
@silvelo 

I just used a simple template from the tutorial:

```javascript
const path = require('path');
const nodeExternals = require('webpack-node-externals');
const TsConfigPathsPlugin = require('awesome-typescript-loader').TsConfigPathsPlugin;

module.exports = {
  target: 'node',
  entry: './bin/app.ts',
  externals: [
    nodeExternals(),
  ],
  output: {
    filename: 'app.bundle.js',
    path: path.resolve(__dirname, 'dist'),
  },
  module: {
    rules: [
      {
        test: /\.ts$/,
        use: 'awesome-typescript-loader',
        exclude: /node_modules/,
      },
    ],
  },
  resolve: {
    extensions: [
      '.js',
      '.ts',
    ],
    plugins: [
      new TsConfigPathsPlugin(),
    ],
  },
  devtool: 'source-map',
};

```

**Comment by rodineijf** [comment]
@kamilmysliwiec Can you share your launch.json?
