### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by juandav** [kamilmysliwiec/nest#7]
I would like to participate in collaborating on the project, I suggest that it is important to create a roadmap and an organization for them.

**Comment by kamilmysliwiec** [comment]
Hi @juandav,

Thanks, it means a lot for me! :)
There I answered about collaborating things - https://github.com/kamilmysliwiec/nest/issues/4
There about roadmap - https://github.com/kamilmysliwiec/nest/issues/6
