### ISSUE TITLE
Middleware not being hit for controllers that don't specify route in Controller decorator

### ISSUE THREAD

**Issue by jevenson** [kamilmysliwiec/nest#71]
I noticed during some development that Middleware does not work for controllers that do not specify the base controller route in the Controller decorator. Please see this branch in my repository for reproduction:

https://github.com/jevenson/nest-testing/tree/bug-report

If you hit `/working`, you'll get a message back saying the middleware is working from the `AuthMiddleware`.
If you hit `/broken`, you'll get a message from the controller saying the middleware is broken from the `BrokenController`.

To sum up, the below controller will honor the middleware defined in the module.
```
@Controller('working')
export class WorkingController {
    @Get()
    public async index(@Response() res) {
        // This should never be hit
        res.status(HttpStatus.OK).json("Middleware is broke!");
    }
}
```
but the below code _won't_.
```
@Controller()
export class BrokenController {
    @Get('broken')
    public async index(@Response() res) {
        // This should never be hit, but is is
        res.status(HttpStatus.OK).json("Middleware is broke!");
    }
}
```

**Comment by kamilmysliwiec** [comment]
Hi @jevenson,
You're right, thanks! Please, update your packages into `2.1.0` version. Issue is fixed.

**Comment by jevenson** [comment]
Thanks @kamilmysliwiec! I tried to investigate a fix on my own, but I had no idea what I was doing in there... haha

**Comment by kamilmysliwiec** [comment]
Haha :smile_cat:
