### ISSUE TITLE
[Question] HttpException part of core package

### ISSUE THREAD

**Issue by JulianBiermann** [kamilmysliwiec/nest#72]
Hi,

I have a question regarding the new module structure.
Is it intended that the **HttpException** class is part of the **nestjs/core** instead of the **nestjs/common** package?

This seems a bit odd to me as I expect the HttpException to be part of the common package.

**Comment by kamilmysliwiec** [comment]
Hi @JulianBiermann,
You're right, it can be a little bit unintuitive, but I don't want to move it, because it will be some kind of 'breaking change'. I have been wondering about an alias of `HttpException` in `@nestjs/common` package, but it also might be weird

**Comment by cojack** [comment]
@kamilmysliwiec maybe when nest will grow up in the time, around next major release there will show up requirements for split some classes into fe: `@nest/http` module. For me, nest is a perfect solution to work with node, but not necessary with http protocol.

Regards.

**Comment by kamilmysliwiec** [comment]
Hi guys,
At the moment I don't plan to move any classes, just to avoid the mess.
