### ISSUE TITLE
[Bug] Middleware forRoutes object.method: 'POST' only accepts numeric values

### ISSUE THREAD

**Issue by JulianBiermann** [kamilmysliwiec/nest#73]
Hi,

I found a bug regarding the application of middleware using the object notation.

I got the following code here:

```typescript
export class UserModule {
  public configure(consumer: MiddlewaresConsumer): void {
    consumer.apply(JwtAuthenticationStrategy).forRoutes(UserController);
    consumer.apply(UserValidationMiddleware).forRoutes({path: '/user', method: 'GET'});
    consumer.apply(UserGenerateValidationMiddleware).forRoutes({path: '/user/generate', method: 'POST'});
  }
}
```

- The application of the **JwtAuthenticationMiddleware** is working
- The application of the **UserValidationMiddleware** is working
- The application of the **UserGenerateValidationMiddleware** is **NOT** working!

The last middleware is not triggered when entering the route. However if I change the method value to the following it works:

```typescript
export class UserModule {
  public configure(consumer: MiddlewaresConsumer): void {
    consumer.apply(JwtAuthenticationStrategy).forRoutes(UserController);
    consumer.apply(UserValidationMiddleware).forRoutes({path: '/user', method: 'GET'});
    consumer.apply(UserGenerateValidationMiddleware).forRoutes({path: '/user/generate', method: 1});
  }
}
```

I changed the string POST to the numeric value 1 which seems to represent the POST method.

**Comment by kamilmysliwiec** [comment]
Hi @JulianBiermann,
It is not a bug. You should use `RequestMethod.POST` instead of plain strings ('POST').

**Comment by JulianBiermann** [comment]
Thanks for letting me know.
