### ISSUE TITLE
[BUG] Cannot find module 'socket.io-client/package' from 'index.js' when testing with JEST

### ISSUE THREAD

**Issue by Martodox** [kamilmysliwiec/nest#74]
Hi guys.
I've found a bizarre bug (or maybe not :D )

I you are testing a component with JEST using @nest/testing helper and use HttpException from '@nestjs/core' JEST tests fail when the component is created with the error above.

So, steps to reproduce:

1. create nest component
2. add a method that throws HttpException
3. set up JEST testing env
4. create test module with createTestingModule method
5. run JEST

This will make JEST fail and now even go to the test suites.

**Comment by jakub-gawlas** [comment]
hi @Martodox 😄 
I had the same error while using *Jest* (https://github.com/kamilmysliwiec/nest/issues/35), solution was add `json` to *moduleFileExtensions* in **Jest** config, maybe will work for you too.

Cheers 🥂

**Comment by Martodox** [comment]
I'll try on Monday.
@kamilmysliwiec Any ideas on official testing guide?

**Comment by Martodox** [comment]
@jakub-gawlas Thanks. That was it. Works like a charm
