### ISSUE TITLE
Component per request - Dependency injection 

### ISSUE THREAD

**Issue by xnramx** [kamilmysliwiec/nest#77]
Is there any way to create a component per request? 
(like CastleWindsor: https://github.com/castleproject/Windsor/blob/master/docs/lifestyles.md )

**Comment by kamilmysliwiec** [comment]
Hi @xnramx,
It is not possible. Components can be singletons across - (1) modules, (2) few modules namespaces (with `@Shared('namespace')`), or entire application (`@Shared()` without namespace).

**Comment by NicolasCharpentier** [comment]
Will you consider it ?

Component per request is an important thing imo.

(Tags for other Googlers as me : component inject request scope dependency nest scoped injection )
