### ISSUE TITLE
Typescript noImplicitAny compatibility

### ISSUE THREAD

**Issue by Ownelek** [kamilmysliwiec/nest#81]
It would be good if nestjs could support different typescript configurations.
Right now using noImplicitAny option in my project generates errors.

**Comment by cojack** [comment]
@Ownelek so, if you are using the `noImplicitAny` flag then you might looking for `suppressImplicitAnyIndexErrors` flag and set it to `true`. There is no correct flag for this option. And there is no one way for using this, all of them depends on you.

https://angular.io/docs/ts/latest/guide/typescript-configuration.html#!#-noimplicitany-and-suppressimplicitanyindexerrors-

Regards.

**Comment by kamilmysliwiec** [comment]
Hi @Ownelek,
Hope the @cojack answer helps you. Unfortunately, it's not easy to avoid `any` types, cause we're addicted to 3rd-party libs.

**Comment by bradleyayers** [comment]
@kamilmysliwiec it's not necessary to avoid `any` types, it's just necessary to avoid *implicit* any types. A path forward here to support more strict users of the library is to turn implicit `any` into explicit via `: any`.

**Comment by Brooooooklyn** [comment]
in typescript 2.5.2, `suppressImplicitAnyIndexErrors` not help when `strict` on.
so would you please mark any params explicit.

**Comment by pawaclawczyk** [comment]
@kamilmysliwiec Is it fine to provide PR with `any` typing on those variable?
It would be great if framework would not enforce changing compiler options.
Can this issue be reopen?

**Comment by wbhob** [comment]
@pawaclawczyk I'll review your PR and if you don't change anything else, I'm sure it will get merged. As much as you can, though, try to type things.

**Comment by smithdalec** [comment]
FYI a workaround is to use the `"skipLibCheck": true` option in your `tsconfig.json`. That way, you can still have the nice `noImplicitAny` type safety in your project, but allows usages of libraries which use `.d.ts` files that don't have `noImplicitAny` checks.
