### ISSUE TITLE
Microservice TCP server does not respond with error

### ISSUE THREAD

**Issue by artaommahe** [kamilmysliwiec/nest#83]
```ts
  @MessagePattern('test')
  public test(): void {

    const error = { message: 'error' };
    const result = undefined;

    respond(error, result);
  }
```
This will respond as success and `{ message: 'error' }` data instead of error in client Observable.
Looks like this check is incorrect.
https://github.com/kamilmysliwiec/nest/blob/master/src/microservices/server/server-tcp.ts#L44

**Comment by kamilmysliwiec** [comment]
Hi @artaommahe,
Since `3.0.0` the `respond()` function doesn't exists, so the issue is fixed :cat:
