### ISSUE TITLE
Add response error type support for `client.send()` method

### ISSUE THREAD

**Issue by artaommahe** [kamilmysliwiec/nest#85]
For proper response error typings `client.send()` should support 2 generics - for success and error response (with default any)
```ts
this.client.send<IUser, IRequestResponse>(pattern, data)
  // `error.message` will be autocompleted due to known typings instead of any
  .do(null, error => console.log(error.message));
```
This will be a bit more useful than
```ts
  .do(null, (error: IRequestResponse) => console.log(error.message));
```
for each error handling operator.

**Comment by kamilmysliwiec** [comment]
Hi @artaommahe,
We are addicted to Rxjs package. They don't support `Observable` error typing (maybe I'm wrong?)
