### ISSUE TITLE
NestMiddleware support asynchronous methods

### ISSUE THREAD

**Issue by StrikeForceZero** [kamilmysliwiec/nest#89]
It would be awesome if `NestMiddleware` could support 
```typescript
export interface NestMiddleware {
    resolve(...args: any[]): Promise<Express.RequestHandler> | Express.RequestHandler;
}
```
by checking to see if they are returning a promise and awaiting them.

**Comment by kamilmysliwiec** [comment]
Hi @StrikeForceZero,
Actually, Nest supports async middlewares

**Comment by StrikeForceZero** [comment]
I meant the resolving of middleware during application setup

**Comment by kamilmysliwiec** [comment]
hey @StrikeForceZero,
could you show any use-case?

**Comment by cojack** [comment]
@StrikeForceZero I think you're looking for #86

**Comment by StrikeForceZero** [comment]
I actually don't have any the moment since middle-ware can be dependency injected.

But originally I was seeking asynchronous behavior in the resolve method using express-session with persistent storage (express-session-mysql in this case).

I was passing the configuration options when the middleware was being applied to the consumer in a module and then performing the setup inside the middleware's `resolve` method. Since it does't support dynamically awaiting with a return type of `Promise<Express.RequestHandler> | Express.RequestHandler` typescript would complain. The dependency injection is an ok stop gap for now, but still makes it difficult to boot up a persistent storage solution before the NestApplication calls listen as it has to be loaded before nest starts configuring.

@cojack A configuration phase could potentially be the more appropriate answer, thanks for linking.

**Comment by kamilmysliwiec** [comment]
Hi @StrikeForceZero,
In the nearest release it'd be possible to return *Promise* inside the middleware's `resolve` method.

**Comment by kamilmysliwiec** [comment]
Hi @StrikeForceZero,
It's possible since v4. Enjoy! :cat:
