### ISSUE TITLE
body-parser (version 1.17.2) issue

### ISSUE THREAD

**Issue by laurensvanpoucke** [kamilmysliwiec/nest#90]
App crashes after body-parser install:

Mon, 12 Jun 2017 22:02:40 GMT body-parser deprecated bodyParser: use individual json/urlencoded middlewares at node_modules/express/lib/router/layer.js:95:5
Mon, 12 Jun 2017 22:02:40 GMT express deprecated req.host: Use req.hostname instead at node_modules/body-parser/index.js:100:29
Mon, 12 Jun 2017 22:02:40 GMT body-parser deprecated undefined extended: provide extended option at node_modules/body-parser/index.js:105:29

**Comment by ThomRick** [comment]
Hey @laurensvanpoucke,

Do you use the express body parser ?
Can you publish the code where you declare the body parser middleware ?

**Comment by laurensvanpoucke** [comment]
hej @ThomRick . Indeed, I'm using the express body parser.

"body-parser": "^1.17.2"

**Comment by laurensvanpoucke** [comment]
@ThomRick Update, it works now... Don't know what I was doing wrong previous time. Thanks for helping!

**Comment by ThomRick** [comment]
Hey @laurensvanpoucke, ok that was weird...
I'll try to reproduce the issue with your previous body-parser version to understand why.

**Comment by cojack** [comment]
@laurensvanpoucke it might be related: https://stackoverflow.com/questions/24330014/bodyparser-is-deprecated-express-4 

`@ThomRick Update, it works now... Don't know what I was doing wrong previous time. Thanks for helping!`

This kind of information, does not help at all, what did you change, do, switch, process?

@ThomRick up^

**Comment by Jucesr** [comment]
I got the same problem. it was because I forgot to take call .json().

**Before**
`app.use(bodyParser);`

**After**
`app.use(bodyParser.json());`
