### ISSUE TITLE
RPC request error `There is no equivalent message pattern`

### ISSUE THREAD

**Issue by artaommahe** [kamilmysliwiec/nest#91]
Two services: `auth` and `thirdparty-vk`. I want to login user from `thirdparty` service via `auth` service RPC method with mesage pattern `LOGIN`.
`auth` server handler
```ts
  @MessagePattern(AUTH_RPC_CONFIG.actions.login)
  public login(userId: number): Observable<IAuthLoginResponse> {

    return this.authService.login(userId);
  }
```
`auth` client service part (injected into `thirdparty` service to request `auth` RPC server)
```ts
  @Client({ transport: Transport.TCP, port: AUTH_APP_CONFIG.rpcPort })
  private client: ClientProxy;

  public login(userId: number): Observable<IAuthLoginResponse> {

    const pattern = AUTH_RPC_CONFIG.actions.login;
    const data = userId;

    return this.client.send<IAuthLoginResponse>(pattern, data)
      .do(() => undefined, error => console.log({ error, pattern, data })); // (2)
  }
```

Added to `@nestjs/microservices/server/server-tcp.js` debug
```js
    handleMessage(socket, msg) {
        const pattern = JSON.stringify(msg.pattern);
console.log('handleMessage', { msg }); // (1)
console.log({ pattern });
```

Then i request `auth` RPC login method and have this in console (without any service restart)

#### first request
`auth` service RPC server log (1)
```
handleMessage { msg: { pattern: 'LOGIN', data: 3 } }
{ pattern: '"LOGIN"' }

handleMessage { msg: 
   { success: false,
     error: 'TypeError: socket.close is not a function' } }
{ pattern: undefined }
```
#### second request
`auth` service RPC server log (1)
```
handleMessage { msg: { pattern: 'LOGIN', data: 3 } }
{ pattern: '"LOGIN"' }

handleMessage { msg: 
   { success: false,
     error: 'Error: Can\'t set headers after they are sent.' } }
{ pattern: undefined }
```
rpc client log (2)
```
{ error: 'There is no equivalent message pattern.',
  pattern: 'LOGIN',
  data: 3 }
```

#### and third request
`auth` service RPC server log (1)
```
handleMessage { msg: { pattern: 'LOGIN', data: 3 } }
{ pattern: '"LOGIN"' }

handleMessage { msg: 
   { success: false,
     error: 'TypeError: socket.close is not a function' } }
{ pattern: undefined }
```
rpc client log (2)
```
{ error: 'There is no equivalent message pattern.',
  pattern: 'LOGIN',
  data: 3 }
```

Next requests response randomly as second or third one. First request does not have client error.

Also `auth` service on login requests `user` service via RPC for user data. `user` service RPC server log on each request looks like this
```
handleMessage { msg: { pattern: 'GET', data: { id: 3 } } }
{ pattern: '"GET"' }

handleMessage { msg: 
   { success: false,
     error: 'TypeError: socket.close is not a function' } }
{ pattern: undefined }
```

Two `handleMessage` parts in debug on request is not typo, it's real debug data on each single request.

**Comment by kamilmysliwiec** [comment]
Hey @artaommahe ,
Thanks for reporting the issue. Let's update your `@nestjs/core` into `3.0.1` version.
