### ISSUE TITLE
Pipes for ws and rpc calls

### ISSUE THREAD

**Issue by artaommahe** [kamilmysliwiec/nest#92]
Same case as for http - validate input params )

**Comment by kamilmysliwiec** [comment]
hey @artaommahe ,
what if pipe throws an exception in ws case?

**Comment by artaommahe** [comment]
@kamilmysliwiec yep, but response format is good question ) I dont know if there is some best practice for ws response format. In my projects i use this one
```typescript
interface IWsSuccessResponse {
  status: 'ok';
  result: Object | Array | null;
}
interface IWsErrorResponse {
  status: 'error';
  result: { message: string };
}
```

**Comment by kamilmysliwiec** [comment]
hi @artaommahe,
it'd be possible since the nearest release - you would be able to use pipes, filters and guards also (new feature).

**Comment by kamilmysliwiec** [comment]
Hi @artaommahe,
The v4 is published now. Enjoy! :cat:
