### ISSUE TITLE
Add decorator after @Get

### ISSUE THREAD

**Issue by silvelo** [kamilmysliwiec/nest#94]
Its posible add my own decorator after @Get decorator?  Because when I do this res seems to be not linked with express response

```typescript
  @Get()
  @Decorator()
  public async getAll( @Res() res: Response) {
    res.status(HttpStatus.OK).send();
```

Update:
Watching [this](https://github.com/kamilmysliwiec/nest/blob/master/src/common/utils/decorators/exception-filters.decorator.ts) I think it can be posible

**Comment by cojack** [comment]
@silvelo show the code

**Comment by silvelo** [comment]
My Decorator:
```
import { ROLE } from "./../shared/enums";
import { ForbiddenException } from './../shared/exceptions';

export function Roles(roles?: ROLE[]) {
  return (
    target: any,
    propertyKey: string,
    descriptor: TypedPropertyDescriptor<any>
  ): TypedPropertyDescriptor<any> => {
    const originalMethod = descriptor.value;
    descriptor.value = function(...args: any[]) {
      const user = args[0];
      let isAuthorized = true;
      if (roles) {
        isAuthorized = roles.some(rol => {
          return user.roles.some(userRol => {
            return userRol === rol;
          });
        });
      }
      if (!isAuthorized) {
        throw new ForbiddenException('No enogugh rol');
      }
      const result = originalMethod.apply(this);
      return result;
    };
    return descriptor;
  };
}
```
And my function:
```
@Get()
@Roles()
  public async getAll( @Res() res: Response) {
    res.status(HttpStatus.OK).send();
}
```

**Comment by cojack** [comment]
@silvelo imo this kind of action should be done in middleware not from decorator

**Comment by ThomRick** [comment]
Hey @silvelo ! 
At first I join @cojack it seems that you want to use a middleware.
But if you want to make decorators combinations you may look at decorator mixin.
There is an example here https://medium.com/@dmyl/mixins-as-class-decorators-in-typescript-angular2-8e09f1bc1f02
But I think there are a plenty of examples that you can find ;-)

**Comment by silvelo** [comment]
@ThomRick yeah, at the first time i used middlewares but that looks very confuse, because the we had a lot of combines and that result add 2 or 4 middlewares per module, because we have 5 roles.
For that we thought to do at this way using decorators and put in controllers, this bring two improve: 
* A clean code because in own case we repeat the middleware a lot of times, for each module.
* Make more easy reas the code.

Thanks for quickly reply.

**Comment by ThomRick** [comment]
Hey @silvelo !
I understand that problem cause I had to face it in a previous professional project but it was written in Java :-)
We used a method decorator by passing each role in an array we want to let pass through like you want to in your case.
That's better than a middleware because it's customizable by request.
So I think you should look at the mixin.

I'll try to make an example with mixin and why not tell to @kamilmysliwiec to integrate mixin in Nest to add custom decorators ;-)

**Comment by silvelo** [comment]
@ThomRick  this will be great.

Thanks for all.

**Comment by FranciZ** [comment]
@silvelo @ThomRick I'm facing a similar dilemma. I want to have transparent route handling and plug authentication and role checking per route in the controller in most cases. Not sure what the advantage is of having this logic separated in another file (Module) and paths redefined in two places.

Something like the UseMiddlewares decorator as below.

```
  @Delete('v1/user/:userId')
  @Middlewares(new AuthMiddleware(['ADMIN']))
  public async deleteUser(@Req() req: IRequest, @Res() res: Response, @Param() reqParams: VDeleteUser): Promise<any> {
    const userId = reqParams.userId;
    const removedUser = await this.userService.remove(userId);
    if (removedUser === null) return this.responseService.error({
      res,
      code: HttpStatus.NOT_FOUND,
      data: { _id: userId }
    });
    this.responseService.success({ res, data: { _id: userId } });
  }
```

**Comment by silvelo** [comment]
@FranciZ looks good .

**Comment by FranciZ** [comment]
I started working on an implementation but am not yet sure how decorators plug into DI so that they are applied to the instance and not only to the class. Any pointers would be appreciated here.

**Comment by cojack** [comment]
@FranciZ maybe instead of passing middlewares just right into controller file (because it will grow and grow...), setup them into module, fe:

```typescript
import { Module, MiddlewaresConsumer } from '@nestjs/common';

@Module({
    controllers: [ UsersController ], // your controller
    components: [ UsersService ],
    exports: [ UsersService ],
})
export class UsersModule {
    configure(consumer: MiddlewaresConsumer) {
        const roles = ['admin''];
        const options = {};
        consumer.apply(AuthMiddleware)
            .with(roles, options)
            .forRoutes({path: 'v1/user/:userId', method: RequestMethod.DELETE});
    }
}
```

Module file is a great place for kind of this actions. Please fallow this link https://docs.nestjs.com/quick-start/middlewares.html to get more examples.

**Comment by FranciZ** [comment]
@cojack Thanks, but I'm aware of this. I'd still rather have the option to apply middleware in the controller since it'll be much more transparent. I see usefulness in defining middleware in the module if it's for all the routes of a controller or something more general. But for things like role specific access control and authentication it's much more transparent to add it as a decorator in controller imo. Having to define paths and methods affected in two different places is also something I'd rather avoid.

**Comment by silvelo** [comment]
@cojack In my project I have this module and works fine
```typescript
export class UsersModule implements NestModule {
    public configure(consumer: MiddlewaresConsumer) {
        consumer
            .apply(AuthMiddleware)
            .forRoutes(
            { path: '/users', method: RequestMethod.GET },
            { path: '/users/:id', method: RequestMethod.DELETE },
            { path: '/users/:id/favorites', method: RequestMethod.PATCH },
            { path: '/users/:id/state', method: RequestMethod.PATCH },
            { path: '/users/:id/role', method: RequestMethod.PATCH })
            .apply(RolesMiddleware)
            .with([ROLE.ADMIN])
            .forRoutes(
            { path: '/users', method: RequestMethod.GET },
            { path: '/users/:id/state', method: RequestMethod.PATCH },
            { path: '/users/:id/role', method: RequestMethod.PATCH })
            .apply(RolesMiddleware)
            .with([ROLE.USER])
            .forRoutes({ path: '/users/:id/favorites', method: RequestMethod.PATCH })
            .apply(RolesMiddleware)
            .with([])
            .forRoutes({ path: '/users/:id', method: RequestMethod.DELETE });
    }
}
```

But this is so confuse and grow a lot, much than the other way, @FranciZ  and me comment

**Comment by FranciZ** [comment]
Is there any chance this might get some attention? As it is, I find this (middlewares) the weakest point of the framework. I'm having a really hard time to justify repeating myself in the Module and in the controller for something that is essentially related and belongs in the same place.

Is the only fear a bloated controller or is there some other reason why this would not be suitable?

**Comment by Masterrg** [comment]
I would love to see such a feature too. We are currently working on a system that doesn't take the user role into account but a specific access right. 

As we got a lot of routes already it isn't really handy to configure and maintain every single path within a module. It would be a lot easier to deal with, if we could add it as a @Decorator directly to the specific route within the controller.

**Comment by adrien2p** [comment]
Hey ! I think you talking about guard that will add in v4 release

**Comment by Masterrg** [comment]
@adrien2p thanks for the hint, just found it in the v4 commits, thank you very much! :)

**Comment by BruceHem** [comment]
Can't wait 😊 for v4, I posted this same problem about defining middlewares in modules on Gitter.
