### ISSUE TITLE
@UseFilters() dont work in middleware

### ISSUE THREAD

**Issue by silvelo** [kamilmysliwiec/nest#95]
When @Middleware throw exception, my own @UserFilters doesnt catch the error, ExceptionsHandler is throw the error.

**Comment by ThomRick** [comment]
Hey @silvelo ! Can you give us the code sample ?

**Comment by silvelo** [comment]
@ThomRick Hi I upload a repo with example https://github.com/silvelo/nestexception.

This server example contains two url to test both with fails, one its correct and the other not.

The first url fail in controller and my OwnfilterException catch the error, but the second the error was in middleware and my filterException doesnt catch

**Comment by kamilmysliwiec** [comment]
Hey @silvelo,
Thanks for reporting the issue. Let's update your `@nestjs/core` into `3.0.1` version.

**Comment by silvelo** [comment]
Thanks for quick reply .
