### ISSUE TITLE
Middleware in ES2015

### ISSUE THREAD

**Issue by juandav** [kamilmysliwiec/nest#99]
I have a question about the use of middleware in ES2015. Typescript accepts interfaces but javascript does not, what can be done about it?

This in ES2015 cannot be done, what would be the correct syntax?
For example in the documentation this:
````typescript

import { Middleware, NestMiddleware } from '@nestjs/common';

@Middleware()
export class LoggingMiddleware implements NestMiddleware {
    resolve(): (req, res, next) => void {
        return (req, res, next) => {
            console.log('Request...');
            next();
        }
    }
}
````

**Comment by cojack** [comment]
> what can be done about it?

Nothing, this is only checked by typescript compiler.

@juandav Check how the `NestMiddleware` interface is compiled to es6:
```javascript
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
```
This is the whole file called `nest-middleware.interface.js`

Btw I recommend to write code in TypeScript using nest.js is perfect combination.

Regards.

**Comment by kamilmysliwiec** [comment]
Hi @juandav,
As @cojack mentioned - just remove typings. In your case:

```typescript
mport { Middleware, NestMiddleware } from '@nestjs/common';

@Middleware()
export class LoggingMiddleware {
    resolve() {
        return (req, res, next) => {
            console.log('Request...');
            next();
        }
    }
}
```
